version: '3'

services:
  web:
    build: .
    container_name: php
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_HOST: '%'
      MYSQL_INIT_CONNECT: 'SET GLOBAL allow_public_key_retrieval = 1'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker-config/nginx-config.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - web