version: '3'

services:
  web:
    build: .
    container_name: php
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker-config/nginx-config.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - web